name: Product Service CI

on:
  push:
    paths:
      - 'services/product-service-nodejs/**'
    branches:
      - main
  pull_request:
    paths:
      - 'services/product-service-nodejs/**'
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install
      working-directory: ./services/product-service-nodejs

    - name: Run tests
      run: npm test
      working-directory: ./services/product-service-nodejs

    - name: Build Docker image
      run: docker build -t product-service:latest ./services/product-service-nodejs

