name: User Service CI

on:
  push:
    paths:
      - 'services/user-service-python/**'
    branches:
      - main
  pull_request:
    paths:
      - 'services/user-service-python/**'
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt
      working-directory: ./services/user-service-python

    - name: Run tests
      run: pytest
      working-directory: ./services/user-service-python

    - name: Build Docker image
      run: docker build -t user-service:latest ./services/user-service-python

